sudo: required
dist: trusty
branches:
  only:
  - master
language: node_js
node_js:
  - stable
cache: yarn
notifications:
  email: false
script:
    - ./compiler.sh
before_install:
    - openssl aes-256-cbc -K $encrypted_563cf4226482_key -iv $encrypted_563cf4226482_iv -in deploy_key.enc -out .deploy_key -d
